name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Google Chrome
        run: |
          # Attempt to install a stable version of Chrome
          wget -q -O google-chrome-stable_current_amd64.deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" || {
            echo "Failed to download Google Chrome."
            exit 1
          }
          sudo dpkg -i google-chrome-stable_current_amd64.deb || {
            echo "Failed to install Google Chrome."
            sudo apt-get install -y -f
            exit 1
          }

      - name: Install ChromeDriver
        run: |
          # Get the version of Google Chrome installed
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+') 
          echo "Detected Chrome version: $CHROME_VERSION"
          # Download the matching ChromeDriver version
          wget -q "https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip" || {
            echo "Failed to download ChromeDriver."
            exit 1
          }
          unzip -o chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify Chrome installation
        run: |
          echo "Checking Google Chrome version:"
          google-chrome --version || echo "Google Chrome not found"
          echo "Checking Chrome binary location:"
          which google-chrome || echo "Google Chrome binary not found"

      - name: Verify ChromeDriver installation
        run: |
          echo "Checking ChromeDriver version:"
          chromedriver --version || echo "ChromeDriver not found"
          echo "Checking ChromeDriver binary location:"
          which chromedriver || echo "ChromeDriver binary not found"

      - name: Run tests
        env:
          DISPLAY: :99.0
          CHROME_BIN: /usr/bin/google-chrome
          PATH: /usr/local/bin:$PATH
        run: |
          python -m pytest tests/ || echo "Tests failed"

      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          to: poojisingh8982@gmail.com
          subject: 'GitHub Actions CI Failure'
          body: 'The CI build has failed. Please check the details.'
          from: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          smtp-server: smtp.gmail.com
          smtp-port: 587
