name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Google Chrome 130.0.6723.69
        run: |
          CHROME_DEB="google-chrome-stable_130.0.6723.69-1_amd64.deb"
          wget -q -O $CHROME_DEB "https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/$CHROME_DEB" || {
            echo "Failed to download Google Chrome."
            exit 1
          }
          sudo dpkg -i $CHROME_DEB || {
            echo "Failed to install Google Chrome."
            sudo apt-get install -y -f
            exit 1
          }

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION="130.0.6723.69"
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$(echo $CHROME_VERSION | cut -d '.' -f 1-2)" || echo "not_found")
          if [ "$CHROMEDRIVER_VERSION" = "not_found" ]; then
            echo "Failed to find a compatible ChromeDriver version for Chrome $CHROME_VERSION."
            exit 1
          fi
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" || {
            echo "Failed to download ChromeDriver."
            exit 1
          }
          unzip -o chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify Chrome installation
        run: |
          echo "Checking Google Chrome version:"
          google-chrome --
