name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          # Install ChromeDriver
          sudo apt-get install -y chromium-chromedriver

      - name: Set Chrome Environment Variables
        run: |
          echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
          echo "CHROME_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Verify Chrome installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run tests
        env:
          DISPLAY: :99.0
        run: |
          python -m pytest tests/ || echo "Tests failed"

      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          to: poojisingh8982@gmail.com
          subject: 'GitHub Actions CI Failure'
          body: 'The CI build has failed. Please check the details.'
          from: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          smtp-server: smtp.gmail.com
          smtp-port: 587
