name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome (specific version)
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          sudo apt-get update
          sudo apt-get install -y wget
          # Download a specific version of Google Chrome (118)
          if ! wget -q https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_118.0.5993.90-1_amd64.deb; then
            echo "Failed to download Google Chrome."
            exit 1
          fi
          if ! sudo dpkg -i google-chrome-stable_118.0.5993.90-1_amd64.deb; then
            echo "Failed to install Google Chrome. Attempting to fix broken dependencies."
            sudo apt-get install -y -f
          fi

      - name: Install ChromeDriver (specific version)
        run: |
          if ! wget -q https://chromedriver.storage.googleapis.com/118.0.5993.90/chromedriver_linux64.zip; then
            echo "Failed to download ChromeDriver."
            exit 1
          fi
          unzip -o chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify Chrome installation
        run: |
          echo "Checking Google Chrome version:"
          if ! google-chrome --version; then
            echo "Google Chrome not found"
          fi
          echo "Checking Chrome binary location:"
          which google-chrome || echo "Google Chrome binary not found"

      - name: Verify ChromeDriver installation
        run: |
          echo "Checking ChromeDriver version:"
          if ! chromedriver --version; then
            echo "ChromeDriver not found"
          fi
          echo "Checking ChromeDriver binary location:"
          which chromedriver || echo "ChromeDriver binary not found"

      - name: Run tests
        env:
          DISPLAY: :99.0
          CHROME_BIN: /usr/bin/google-chrome
          PATH: /usr/local/bin:$PATH
        run: |
          python -m pytest tests/ || echo "Tests failed"

      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          to: poojisingh8982@gmail.com
          subject: 'GitHub Actions CI Failure'
          body: 'The CI build has failed. Please check the details.'
          from: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          smtp-server: smtp.gmail.com
          smtp-port: 587
