name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Send notification
        if: failure()
        run: |
          python -c "
          import smtplib
          from email.mime.text import MIMEText

          msg = MIMEText('Test failed!')
          msg['Subject'] = 'CI/CD Pipeline Notification'
          msg['From'] = 'poojisingh8982@gmail.com'
          msg['To'] = 'poojisingh8982@gmail.com'

          with smtplib.SMTP('smtp.gmail.com', 587) as server:
              server.starttls()
              server.login('poojisingh8982@gmail.com', 'your-email-password')  
              server.send_message(msg)
          "
