name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -y -f

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -o '[0-9]*\.[0-9]*\.[0-9]*' | head -1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify Chrome installation
        run: |
          google-chrome --version
          which google-chrome
          ls -l /usr/bin/google-chrome

      - name: Run tests
        env:
          DISPLAY: :99.0
          CHROME_BIN: /usr/bin/google-chrome
          PATH: /usr/local/bin:$PATH
        run: |
          python -m pytest tests/ || echo "Tests failed"

      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          to: poojisingh8982@gmail.com
          subject: 'GitHub Actions CI Failure'
          body: 'The CI build has failed. Please check the details.'
          from: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          smtp-server: smtp.gmail.com
          smtp-port: 587
